id: P503C75A4
initial_creation_type: ocr
source_metadata:
  volumes:
    bb5dac802b714ed6a45b5c03695f75e9:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་རྡོ་རྗེ་གཅོད་པའི་དོན་བདུན་གྱི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
